version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on: # 追加
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    build: .
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: common
      MYSQL_USER: ken
      MYSQL_PASSWORD: Ken19886032
      MYSQL_ROOT_PASSWORD: Ken19886032
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
